### ISSUE TITLE
requirements.txt | Can you include requirements or installed package verisons to avoide ModuleNotFoundError

### ISSUE THREAD

**Issue by ramees-kr** [pl238dk/framework_netmri#1]
```
    from timestamp.timestamp import timestamp
ModuleNotFoundError: No module named 'timestamp.timestamp'; 'timestamp' is not a package
```
I tried installing module timestamp, https://pypi.org/project/timestamp/
However, I am getting the same error as shown above

**Comment by ramees-kr** [comment]
Found "timestamp" in your repos. Thank you.

**Comment by pl238dk** [comment]
Oh I'm so sorry! I must have accidentally left that one in there. It really isn't important for function, you can comment it out.

Otherwise, the framework is listed below!

https://github.com/pl238dk/framework_timestamp
________________________________
From: Ramees ***@***.***>
Sent: Tuesday, October 4, 2022 1:06 PM
To: pl238dk/framework_netmri ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pl238dk/framework_netmri] requirements.txt | Can you include requirements or installed package verisons to avoide ModuleNotFoundError (Issue #1)


    from timestamp.timestamp import timestamp
ModuleNotFoundError: No module named 'timestamp.timestamp'; 'timestamp' is not a package


I tried installing module timestamp, https://pypi.org/project/timestamp/
However, I am getting the same error as shown above
